#!/usr/bin/env bash

# 1. Configuration
SUFFIX="_old" 
DWE_YAML="DWE_Camera.yaml"  # Ensure this file exists in ../Examples_old/Monocular/
SEQUENCE="Mecatron_Dataset"       # Label for your output files

# 2. Paths - Pointing to your Downloads folder
# This should be the folder containing the 'mav0' directory
PATH_TO_SEQUENCE_FOLDER="/home/kc/Downloads/AUV_Mecatron_Dataset"
OUTPUT_BASE_NAME="dataset_"$SEQUENCE"_mono"

echo "PATH_TO_SEQUENCE_FOLDER: $PATH_TO_SEQUENCE_FOLDER"
echo "OUTPUT_BASE_NAME: $OUTPUT_BASE_NAME"

# 3. Execution
# We use the Monocular binary because you extracted cam0 only
# The fourth argument is the data.csv generated by your extraction script
../Examples$SUFFIX/Monocular/mono_euroc$SUFFIX \
    ../Vocabulary/ORBvoc.txt \
    ../Examples$SUFFIX/Monocular/$DWE_YAML \
    $PATH_TO_SEQUENCE_FOLDER \
    $PATH_TO_SEQUENCE_FOLDER/mav0/cam0/data.csv \
    $OUTPUT_BASE_NAME

# 4. Evaluation (Commented out)
# These are disabled because they require a reference ground truth file
# echo "" 
# echo "Metric generation skipped (No Ground Truth file for custom AUV data)"
# python evaluate_ate_scale.py ../evaluation/Ground_truth/EuRoC_left_cam/"$SEQUENCE"_GT.txt "f_"$OUTPUT_BASE_NAME".txt" --plot "f_"$OUTPUT_BASE_NAME".pdf"

# 5. Cleanup
./move_output_to_results.sh $OUTPUT_BASE_NAME